# Question:5 
Assignment by: charu saxena(A20378393)

In [3]:
import numpy as np
from numpy import *
from vpython import *

A

In [4]:
A= vector(1,2,3)
B = vector(4,5,6)
C = vector(-1,1,3)


In [5]:
#A1)
(2*A)-B

<-2.000000, -1.000000, 0.000000>

In [10]:
#A2
print("mod of A:",A.mag)
#np.angle(1i+1j+3k, deg=True)
X= vector(1,0,0)
print("angle of A wrt x axis :",math.degrees(A.diff_angle(X)))


mod of A: 3.7416573867739413
angle of A wrt x axis : 74.498640433063


In [11]:
#A3 unit vector

#mag=pow(A,2)+pow(B,2)+pow(C,2)
#denom = pow(mag,1/2)
#unit_vector = np.array ([A/denom])
#unit_vector
unit_vectorA = A.norm()
unit_vectorA


<0.267261, 0.534522, 0.801784>

In [12]:
#A4 directional cosines of A
directional_cosines_for_A = A.norm()
directional_cosines_for_A


<0.267261, 0.534522, 0.801784>

In [13]:
#A5 A.B and B.A
a_dot_b = A.dot(B)
b_dot_a = B.dot(A)
print(a_dot_b)
b_dot_a

32.0


32.0

In [15]:
#A6 angle between A and B
print("angle between A and B",A.diff_angle(B))

angle between A and B 0.2257261285527342


In [19]:
#A7 a vector perpendicular to A
#to find this let one of the vector be D[1,1,1]
#then we will find a vector perpendicular to both A and D which will give 
#our desired answer:
D = vector(1,1,1)
print("vector perpendicular to A is :",A.cross(D))

vector perpendicular to A is : <-1.000000, 2.000000, -1.000000>


In [21]:
#A8 AxB and BXA

print("A cross B is :",A.cross(B))
print("B cross A is :",B.cross(A))

A cross B is : <-3.000000, 6.000000, -3.000000>
B cross A is : <3.000000, -6.000000, 3.000000>


In [23]:
#A9 a vector perpendicular to both A and B

print("vector perpendicular to both a and B is:",cross(A,B))

vector perpendicular to both a and B is: <-3.000000, 6.000000, -3.000000>


In [28]:
#A10 linear dependency
a=np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([-1,1,3])
mat = np.column_stack((a,b,c))
if(np.linalg.det(mat)==0):
    print("they are linear dependent")
else:
    print("they are linear independent")

they are linear independent


In [6]:
#A11
a=np.array([1,2,3])
b= np.array([4,5,6])
A_transpose_B = np.dot(np.transpose(a),b)
B_transpose_A = np.dot(np.transpose(b),a)
print("a trnspose b is : ",A_transpose_B )
print("b trnspose a is : ",B_transpose_A )

a trnspose b is :  32
b trnspose a is :  32


# Question B

In [31]:
#B1 2A-B
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])

print("2A-B is :\n",2*A-B)

2A-B is :
 [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [32]:
#B2 AB and BA

print("AB is :\n",np.dot(A,B))
print("BA is :\n",np.dot(B,A))

AB is :
 [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
BA is :
 [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [33]:
#B3 (AB)transpose and B(transpose)A(transpose)
print("AB tranpose is :\n",np.transpose(np.dot(A,B)))
print("B tranpose dot A transpose is :\n",np.dot(np.transpose(B),np.transpose(A)))

AB tranpose is :
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
B tranpose dot A transpose is :
 [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [34]:
#B4 determinant of A and C

print("A: ",np.linalg.det(A))
print("C: ",np.linalg.det(C))

A:  55.0
C:  7.49400541622e-16


In [40]:
#B5 matrix in which the row vectors are orthogonal
if (np.dot(A[0],A[1])==0 or np.dot(A[0],A[2])==0 or np.dot(A[2],A[1])==0):
    print("matrix A has row vectors orthognal in nature.")
elif (np.dot(B[0],B[1])==0 or np.dot(B[0],B[2])==0 or np.dot(B[2],B[1])==0):
    print("matrix B has row vectors orthognal in nature.")
elif (np.dot(C[0],C[1])==0 or np.dot(C[0],C[2])==0 or np.dot(C[2],C[1])==0):
    print("matrix C has row vectors orthognal in nature.")
else:
    print("none")

matrix B has row vectors orthognal in nature.


In [41]:
#B6 A^-1 and B^-1

print("A inverse: \n",np.linalg.inv(A))
print("B inverse: \n",np.linalg.inv(B))

A inverse: 
 [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
B inverse: 
 [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# Question C:

In [42]:
A = np.array([[1,2],[3,2]])
B = np.array([[2,-2],[-2,5]])

In [43]:
#1 eigen value and vector A

eigen_A,Vectors = np.linalg.eig(A)
print("A eigen values : \n",Vectors)
print("A eigen vectors : \n",eigen_A)

A eigen values : 
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
A eigen vectors : 
 [-1.  4.]


In [48]:
#2 eigen V inverse dot A dot V

print("V^-1 AV:\n", np.dot(np.dot((np.linalg.inv(Vectors)),A),Vectors) )

V^-1 AV:
 [[ -1.00000000e+00  -4.44089210e-16]
 [  0.00000000e+00   4.00000000e+00]]


In [51]:
#3 dot product between eigen-vectors of  A
print("Dot product between eigen vectors of A:\n ",np.dot(Vectors[:,0],Vectors[:,1]))


Dot product between eigen vectors of A:
  -0.196116135138


In [52]:
#4 dot product between eigen-vectors of B

eigen_B,Vectors_B = np.linalg.eig(B)
print("Dot product between eigen vectors of B:\n ",np.dot(Vectors_B[:,0],Vectors_B[:,1]))

Dot product between eigen vectors of B:
  0.0
